name = "watchjob"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

# Konfigurasi Database D1
[[d1_databases]]
binding = "DB"
database_name = "watchjob"
database_id = "4764b48a-a368-45bb-ac01-258b31e6ed1d"
